server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuxiang-git/hello-springcloud.git
          searchPaths: config
          username: yuxiang-git
          password: chenYuxiang1225.
        label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

